SET DATABASE SQL SYNTAX PGS true;
CREATE SEQUENCE sw_accession_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE NO MINVALUE;
ALTER TABLE expense ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE experiment ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE file ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE invoice ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE lims_key ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE ius ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE lane ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE processing ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
-- ALTER TABLE processing_experiments ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
-- ALTER TABLE processing_ius ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
-- ALTER TABLE processing_lanes ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
-- ALTER TABLE processing_samples ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
-- ALTER TABLE processing_sequencer_runs ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
-- ALTER TABLE processing_studies ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE sample ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE sequencer_run ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE share_study ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE share_workflow_run ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE study ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE workflow ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');
ALTER TABLE workflow_run ALTER COLUMN sw_accession SET DEFAULT nextval('sw_accession_seq');